"""API key generation and hashing — pure functions, no DB/FastAPI
dependencies, so they're trivially unit-testable and reusable from both the
admin CLI (app/api_platform/cli.py) and the auth dependency
(app/api_platform/auth.py).

Hashing choice: SHA-256 of the full random token, not bcrypt/argon2/PBKDF2.
Slow password-hashing KDFs exist to compensate for LOW-entropy human
passwords (defending against brute-force guessing of a small keyspace); an
API key generated by `secrets.token_urlsafe(32)` has ~256 bits of entropy —
brute-forcing the hash is already computationally infeasible with a fast
hash, and a slow KDF would only add unnecessary CPU cost to every single
authenticated request for no real security benefit. This is standard
practice for API keys (the same approach GitHub/Stripe-style tokens use).
"""

import hashlib
import secrets

KEY_PREFIX = "afl_"
_TOKEN_BYTES = 32  # secrets.token_urlsafe(32) -> ~43 char token, ~256 bits of entropy
PREFIX_DISPLAY_LENGTH = 12  # how much of the raw key is retained (as key_prefix) for admin identification


def generate_api_key() -> str:
    """Returns a new raw API key. This value is NEVER persisted anywhere —
    only its hash (see hash_key) and its first PREFIX_DISPLAY_LENGTH
    characters (see key_prefix) are stored. The caller must show this to
    the user exactly once, at creation time."""
    return f"{KEY_PREFIX}{secrets.token_urlsafe(_TOKEN_BYTES)}"


def hash_key(raw_key: str) -> str:
    return hashlib.sha256(raw_key.encode("utf-8")).hexdigest()


def key_prefix(raw_key: str) -> str:
    return raw_key[:PREFIX_DISPLAY_LENGTH]
