"""add match context items and venue weather snapshots

Revision ID: 03b8f763abb2
Revises: 4a276e8b7fe4
Create Date: 2026-08-18 15:43:54.336639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b8f763abb2'
down_revision: Union[str, None] = '4a276e8b7fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_context_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('context_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.String(length=300), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_context_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_context_items_context_type'), ['context_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_context_items_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_context_items_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_context_items_team_id'), ['team_id'], unique=False)

    op.create_table('venue_weather_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('rain_probability_pct', sa.Float(), nullable=True),
    sa.Column('expected_rainfall_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_kph', sa.Float(), nullable=True),
    sa.Column('wind_gust_kph', sa.Float(), nullable=True),
    sa.Column('severe_weather_warning', sa.Boolean(), nullable=False),
    sa.Column('severe_weather_note', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venue_weather_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_weather_snapshots_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_venue_weather_snapshots_venue_id'), ['venue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue_weather_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_weather_snapshots_venue_id'))
        batch_op.drop_index(batch_op.f('ix_venue_weather_snapshots_match_id'))

    op.drop_table('venue_weather_snapshots')
    with op.batch_alter_table('match_context_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_context_items_team_id'))
        batch_op.drop_index(batch_op.f('ix_match_context_items_player_id'))
        batch_op.drop_index(batch_op.f('ix_match_context_items_match_id'))
        batch_op.drop_index(batch_op.f('ix_match_context_items_context_type'))

    op.drop_table('match_context_items')
    # ### end Alembic commands ###
