"""add team_match_stats table

Revision ID: 0480a0ebe74a
Revises: 8316cece5ae7
Create Date: 2026-08-15 14:16:03.942687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0480a0ebe74a'
down_revision: Union[str, None] = '8316cece5ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('kicks', sa.Integer(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('handballs', sa.Integer(), nullable=True),
    sa.Column('disposals', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('behinds', sa.Integer(), nullable=True),
    sa.Column('hitouts', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('rebound_50s', sa.Integer(), nullable=True),
    sa.Column('inside_50s', sa.Integer(), nullable=True),
    sa.Column('clearances', sa.Integer(), nullable=True),
    sa.Column('clangers', sa.Integer(), nullable=True),
    sa.Column('frees_for', sa.Integer(), nullable=True),
    sa.Column('frees_against', sa.Integer(), nullable=True),
    sa.Column('brownlow_votes', sa.Integer(), nullable=True),
    sa.Column('contested_possessions', sa.Integer(), nullable=True),
    sa.Column('uncontested_possessions', sa.Integer(), nullable=True),
    sa.Column('contested_marks', sa.Integer(), nullable=True),
    sa.Column('marks_inside_50', sa.Integer(), nullable=True),
    sa.Column('one_percenters', sa.Integer(), nullable=True),
    sa.Column('bounces', sa.Integer(), nullable=True),
    sa.Column('goal_assists', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', 'source', name='uq_team_match_stat_match_team_source')
    )
    with op.batch_alter_table('team_match_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_match_stats_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_match_stats_opponent_team_id'), ['opponent_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_match_stats_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_match_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_match_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_match_stats_opponent_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_match_stats_match_id'))

    op.drop_table('team_match_stats')
    # ### end Alembic commands ###
