"""add player tag annotations

Revision ID: 04b59a8a329c
Revises: 75715f635e7a
Create Date: 2026-09-10 17:33:59.329580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b59a8a329c'
down_revision: Union[str, None] = '75715f635e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_tag_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('tagged_player_id', sa.Integer(), nullable=False),
    sa.Column('tagger_player_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('tagged_duration_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['tagged_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tagger_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_tag_annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_tag_annotations_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_tag_annotations_tagged_player_id'), ['tagged_player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_tag_annotations_tagger_player_id'), ['tagger_player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_tag_annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_tag_annotations_tagger_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_tag_annotations_tagged_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_tag_annotations_match_id'))

    op.drop_table('player_tag_annotations')
    # ### end Alembic commands ###
