"""add players and player_match_stats tables

Revision ID: 04f8e2e7463c
Revises: 10365f5e5d4f
Create Date: 2026-08-15 19:36:51.514738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f8e2e7463c'
down_revision: Union[str, None] = '10365f5e5d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_player_id', sa.String(length=256), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'source', 'source_player_id', name='uq_player_sport_source_id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_current_team_id'), ['current_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_sport_id'), ['sport_id'], unique=False)

    op.create_table('player_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_player_id', sa.String(length=256), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jumper_number', sa.Integer(), nullable=True),
    sa.Column('subbed_on', sa.Boolean(), nullable=False),
    sa.Column('subbed_off', sa.Boolean(), nullable=False),
    sa.Column('kicks', sa.Integer(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('handballs', sa.Integer(), nullable=True),
    sa.Column('disposals', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('behinds', sa.Integer(), nullable=True),
    sa.Column('hitouts', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('rebound_50s', sa.Integer(), nullable=True),
    sa.Column('inside_50s', sa.Integer(), nullable=True),
    sa.Column('clearances', sa.Integer(), nullable=True),
    sa.Column('clangers', sa.Integer(), nullable=True),
    sa.Column('frees_for', sa.Integer(), nullable=True),
    sa.Column('frees_against', sa.Integer(), nullable=True),
    sa.Column('brownlow_votes', sa.Integer(), nullable=True),
    sa.Column('contested_possessions', sa.Integer(), nullable=True),
    sa.Column('uncontested_possessions', sa.Integer(), nullable=True),
    sa.Column('contested_marks', sa.Integer(), nullable=True),
    sa.Column('marks_inside_50', sa.Integer(), nullable=True),
    sa.Column('one_percenters', sa.Integer(), nullable=True),
    sa.Column('bounces', sa.Integer(), nullable=True),
    sa.Column('goal_assists', sa.Integer(), nullable=True),
    sa.Column('time_on_ground_pct', sa.Integer(), nullable=True),
    sa.Column('fantasy_points', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'match_id', 'source', name='uq_player_match_stat_player_match_source')
    )
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_match_stats_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_stats_opponent_team_id'), ['opponent_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_stats_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_match_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_stats_opponent_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_stats_match_id'))

    op.drop_table('player_match_stats')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_sport_id'))
        batch_op.drop_index(batch_op.f('ix_players_display_name'))
        batch_op.drop_index(batch_op.f('ix_players_current_team_id'))

    op.drop_table('players')
    # ### end Alembic commands ###
