"""add model_run_history table

Revision ID: 10365f5e5d4f
Revises: 0480a0ebe74a
Create Date: 2026-08-15 19:18:05.109806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10365f5e5d4f'
down_revision: Union[str, None] = '0480a0ebe74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_run_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('tune_end_year', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_run_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_run_history_model_name'), ['model_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_run_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_run_history_model_name'))

    op.drop_table('model_run_history')
    # ### end Alembic commands ###
