"""add elo_ratings table

Revision ID: 1354f40385f9
Revises: 1a6e6c258d79
Create Date: 2026-08-14 16:41:01.079147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1354f40385f9'
down_revision: Union[str, None] = '1a6e6c258d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elo_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('rating_before', sa.Float(), nullable=False),
    sa.Column('rating_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_elo_rating_match_team')
    )
    with op.batch_alter_table('elo_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elo_ratings_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_elo_ratings_sequence'), ['sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_elo_ratings_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elo_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elo_ratings_team_id'))
        batch_op.drop_index(batch_op.f('ix_elo_ratings_sequence'))
        batch_op.drop_index(batch_op.f('ix_elo_ratings_match_id'))

    op.drop_table('elo_ratings')
    # ### end Alembic commands ###
