"""add selection status and provenance to expected lineups; team model version to projections

Revision ID: 176b3854bd2c
Revises: fda3962cc07c
Create Date: 2026-08-16 17:22:03.915540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176b3854bd2c'
down_revision: Union[str, None] = 'fda3962cc07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expected_lineups', schema=None) as batch_op:
        # server_default backfills existing rows (e.g. the placeholder rows
        # from the prior stage) as 'placeholder'/unconfirmed/not-overridden —
        # an accurate description of what those rows actually are, not just
        # a schema-migration convenience value.
        batch_op.add_column(sa.Column('selection_status', sa.String(length=24), nullable=False, server_default='placeholder'))
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('source_reference', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_manual_override', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('player_disposal_projections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_model_version', sa.String(length=128), nullable=True))

    with op.batch_alter_table('player_goal_projections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_model_version', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_goal_projections', schema=None) as batch_op:
        batch_op.drop_column('team_model_version')

    with op.batch_alter_table('player_disposal_projections', schema=None) as batch_op:
        batch_op.drop_column('team_model_version')

    with op.batch_alter_table('expected_lineups', schema=None) as batch_op:
        batch_op.drop_column('is_manual_override')
        batch_op.drop_column('source_reference')
        batch_op.drop_column('source_timestamp')
        batch_op.drop_column('is_confirmed')
        batch_op.drop_column('selection_status')

    # ### end Alembic commands ###
