"""add placed bets

Revision ID: 1817ff671b79
Revises: e1f2a3b4c5d6
Create Date: 2026-08-23 17:33:07.810204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1817ff671b79'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placed_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('line_type', sa.String(length=16), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('line_value', sa.Float(), nullable=True),
    sa.Column('bookmaker', sa.String(length=64), nullable=False),
    sa.Column('odds_taken', sa.Float(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_mode', sa.String(length=24), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('model_fair_odds', sa.Float(), nullable=False),
    sa.Column('confidence_tier', sa.String(length=24), nullable=False),
    sa.Column('lineup_status', sa.String(length=24), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('actual_stat_value', sa.Float(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('placed_bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placed_bets_market_type'), ['market_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_placed_bets_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_placed_bets_placed_at'), ['placed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_placed_bets_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_placed_bets_source_mode'), ['source_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_placed_bets_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placed_bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placed_bets_status'))
        batch_op.drop_index(batch_op.f('ix_placed_bets_source_mode'))
        batch_op.drop_index(batch_op.f('ix_placed_bets_player_id'))
        batch_op.drop_index(batch_op.f('ix_placed_bets_placed_at'))
        batch_op.drop_index(batch_op.f('ix_placed_bets_match_id'))
        batch_op.drop_index(batch_op.f('ix_placed_bets_market_type'))

    op.drop_table('placed_bets')
    # ### end Alembic commands ###
