"""add nba foundation tables

Revision ID: 1e453acf52cb
Revises: 04b59a8a329c
Create Date: 2026-10-02 14:58:56.510893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e453acf52cb'
down_revision: Union[str, None] = '04b59a8a329c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('abbreviation', sa.String(length=8), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_nba_team_name')
    )
    with op.batch_alter_table('nba_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_teams_abbreviation'), ['abbreviation'], unique=False)

    op.create_table('nba_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_start_year', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.String(length=16), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_game_id', sa.String(length=64), nullable=False),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('home_team_id != away_team_id', name='ck_nba_game_distinct_teams'),
    sa.ForeignKeyConstraint(['away_team_id'], ['nba_teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['nba_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_game_id', name='uq_nba_game_source_id')
    )
    with op.batch_alter_table('nba_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_games_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_games_game_date'), ['game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_games_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_games_scheduled_start'), ['scheduled_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_games_season_start_year'), ['season_start_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_games_status'), ['status'], unique=False)

    op.create_table('nba_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_player_id', sa.String(length=64), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_team_id'], ['nba_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_player_id', name='uq_nba_player_source_id')
    )
    with op.batch_alter_table('nba_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_players_current_team_id'), ['current_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_players_display_name'), ['display_name'], unique=False)

    op.create_table('nba_player_availability_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['nba_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['nba_players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['nba_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nba_player_availability_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_player_availability_reports_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_player_availability_reports_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_player_availability_reports_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_player_availability_reports_team_id'), ['team_id'], unique=False)

    op.create_table('nba_player_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('did_not_play', sa.Boolean(), nullable=False),
    sa.Column('did_not_play_reason', sa.String(length=128), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('field_goals_made', sa.Integer(), nullable=True),
    sa.Column('field_goals_attempted', sa.Integer(), nullable=True),
    sa.Column('three_pointers_made', sa.Integer(), nullable=True),
    sa.Column('three_pointers_attempted', sa.Integer(), nullable=True),
    sa.Column('free_throws_made', sa.Integer(), nullable=True),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('personal_fouls', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['nba_games.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['nba_teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['nba_players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['nba_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', 'source', name='uq_nba_player_game_log_player_game_source')
    )
    with op.batch_alter_table('nba_player_game_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_player_game_logs_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_player_game_logs_opponent_team_id'), ['opponent_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_player_game_logs_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_player_game_logs_team_id'), ['team_id'], unique=False)

    op.create_table('nba_prop_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('information_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_minutes', sa.Float(), nullable=True),
    sa.Column('rate_per_minute', sa.Float(), nullable=True),
    sa.Column('predicted_mean', sa.Float(), nullable=False),
    sa.Column('distribution_kind', sa.String(length=32), nullable=False),
    sa.Column('distribution_params', sa.JSON(), nullable=False),
    sa.Column('games_of_history', sa.Integer(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['nba_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['nba_players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['nba_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', 'market', 'model_version', 'information_cutoff', name='uq_nba_prop_projection_identity')
    )
    with op.batch_alter_table('nba_prop_projections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_prop_projections_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_projections_information_cutoff'), ['information_cutoff'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_projections_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_projections_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_projections_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_projections_team_id'), ['team_id'], unique=False)

    op.create_table('nba_prop_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('selection', sa.String(length=8), nullable=False),
    sa.Column('is_alternate_line', sa.Boolean(), nullable=False),
    sa.Column('price_decimal', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bookmaker_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=64), nullable=True),
    sa.Column('provider_market_key', sa.String(length=48), nullable=True),
    sa.Column('raw_outcome', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['nba_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['nba_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nba_prop_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_prop_quotes_bookmaker_id'), ['bookmaker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_quotes_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_quotes_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_quotes_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_quotes_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_quotes_provider_event_id'), ['provider_event_id'], unique=False)

    op.create_table('nba_prop_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projection_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('selection', sa.String(length=8), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('information_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('model_fair_odds', sa.Float(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipoff_at_prediction', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_bookmaker_id', sa.Integer(), nullable=True),
    sa.Column('entry_quote_id', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('entry_quote_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_consensus_probability', sa.Float(), nullable=True),
    sa.Column('entry_n_bookmakers', sa.Integer(), nullable=True),
    sa.Column('entry_expected_value', sa.Float(), nullable=True),
    sa.Column('closing_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_main_line', sa.Float(), nullable=True),
    sa.Column('closing_price', sa.Float(), nullable=True),
    sa.Column('closing_quote_id', sa.Integer(), nullable=True),
    sa.Column('closing_quote_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_consensus_probability', sa.Float(), nullable=True),
    sa.Column('closing_n_bookmakers', sa.Integer(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('settlement_note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['closing_quote_id'], ['nba_prop_quotes.id'], ),
    sa.ForeignKeyConstraint(['entry_bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['entry_quote_id'], ['nba_prop_quotes.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['nba_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['nba_players.id'], ),
    sa.ForeignKeyConstraint(['projection_id'], ['nba_prop_projections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projection_id', 'line', 'selection', name='uq_nba_prop_prediction_projection_line_selection')
    )
    with op.batch_alter_table('nba_prop_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_prop_predictions_entry_bookmaker_id'), ['entry_bookmaker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_predictions_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_predictions_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_predictions_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_predictions_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_predictions_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_predictions_predicted_at'), ['predicted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_prop_predictions_projection_id'), ['projection_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nba_prop_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_prop_predictions_projection_id'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_predictions_predicted_at'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_predictions_player_id'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_predictions_outcome'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_predictions_model_version'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_predictions_market'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_predictions_game_id'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_predictions_entry_bookmaker_id'))

    op.drop_table('nba_prop_predictions')
    with op.batch_alter_table('nba_prop_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_prop_quotes_provider_event_id'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_quotes_player_id'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_quotes_observed_at'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_quotes_market'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_quotes_game_id'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_quotes_bookmaker_id'))

    op.drop_table('nba_prop_quotes')
    with op.batch_alter_table('nba_prop_projections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_prop_projections_team_id'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_projections_player_id'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_projections_model_version'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_projections_market'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_projections_information_cutoff'))
        batch_op.drop_index(batch_op.f('ix_nba_prop_projections_game_id'))

    op.drop_table('nba_prop_projections')
    with op.batch_alter_table('nba_player_game_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_player_game_logs_team_id'))
        batch_op.drop_index(batch_op.f('ix_nba_player_game_logs_player_id'))
        batch_op.drop_index(batch_op.f('ix_nba_player_game_logs_opponent_team_id'))
        batch_op.drop_index(batch_op.f('ix_nba_player_game_logs_game_id'))

    op.drop_table('nba_player_game_logs')
    with op.batch_alter_table('nba_player_availability_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_player_availability_reports_team_id'))
        batch_op.drop_index(batch_op.f('ix_nba_player_availability_reports_player_id'))
        batch_op.drop_index(batch_op.f('ix_nba_player_availability_reports_observed_at'))
        batch_op.drop_index(batch_op.f('ix_nba_player_availability_reports_game_id'))

    op.drop_table('nba_player_availability_reports')
    with op.batch_alter_table('nba_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_players_display_name'))
        batch_op.drop_index(batch_op.f('ix_nba_players_current_team_id'))

    op.drop_table('nba_players')
    with op.batch_alter_table('nba_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_games_status'))
        batch_op.drop_index(batch_op.f('ix_nba_games_season_start_year'))
        batch_op.drop_index(batch_op.f('ix_nba_games_scheduled_start'))
        batch_op.drop_index(batch_op.f('ix_nba_games_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_nba_games_game_date'))
        batch_op.drop_index(batch_op.f('ix_nba_games_away_team_id'))

    op.drop_table('nba_games')
    with op.batch_alter_table('nba_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_teams_abbreviation'))

    op.drop_table('nba_teams')
    # ### end Alembic commands ###
