"""add anomaly case records

Revision ID: 2de0af8855ae
Revises: b9a43891bad4
Create Date: 2026-08-24 16:44:18.004130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de0af8855ae'
down_revision: Union[str, None] = 'b9a43891bad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_case_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_key', sa.String(length=128), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('n_snapshots', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manual_status', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_key', name='uq_anomaly_case_record_key')
    )
    with op.batch_alter_table('anomaly_case_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_case_records_case_key'), ['case_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_case_records_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_case_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_case_records_match_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_case_records_case_key'))

    op.drop_table('anomaly_case_records')
    # ### end Alembic commands ###
