"""add multi-group and model_version fields to placed_bets

Revision ID: 3d50becab3e5
Revises: 71cdf5905ebf
Create Date: 2026-08-24 19:00:43.921891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d50becab3e5'
down_revision: Union[str, None] = '71cdf5905ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placed_bets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_version', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('multi_group_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('multi_tier', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('multi_indicative_odds', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_placed_bets_multi_group_id'), ['multi_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placed_bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placed_bets_multi_group_id'))
        batch_op.drop_column('multi_indicative_odds')
        batch_op.drop_column('multi_tier')
        batch_op.drop_column('multi_group_id')
        batch_op.drop_column('model_version')

    # ### end Alembic commands ###
