"""add sgm price snapshots

Revision ID: 40dd3e49d0e7
Revises: d135a718cc95
Create Date: 2026-08-31 12:38:48.174976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40dd3e49d0e7'
down_revision: Union[str, None] = 'd135a718cc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgm_price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('leg_signature', sa.String(length=512), nullable=False),
    sa.Column('n_legs', sa.Integer(), nullable=False),
    sa.Column('snapshot_horizon', sa.String(length=16), nullable=False),
    sa.Column('hours_to_kickoff', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=256), nullable=False),
    sa.Column('dependence_coefficients_used', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('naive_independence_probability', sa.Float(), nullable=False),
    sa.Column('correlation_adjustment_pp', sa.Float(), nullable=False),
    sa.Column('model_fair_odds', sa.Float(), nullable=False),
    sa.Column('naive_independence_fair_odds', sa.Float(), nullable=False),
    sa.Column('mc_standard_error', sa.Float(), nullable=False),
    sa.Column('n_simulations', sa.Integer(), nullable=False),
    sa.Column('dependence_validated', sa.Boolean(), nullable=False),
    sa.Column('bookmaker_sgm_price', sa.Float(), nullable=True),
    sa.Column('bookmaker_sgm_name', sa.String(length=64), nullable=True),
    sa.Column('bookmaker_implied_probability', sa.Float(), nullable=True),
    sa.Column('model_edge', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'leg_signature', 'model_version', 'snapshot_horizon', name='uq_sgm_price_snapshot_identity')
    )
    with op.batch_alter_table('sgm_price_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sgm_price_snapshots_leg_signature'), ['leg_signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_sgm_price_snapshots_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sgm_price_snapshots_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_sgm_price_snapshots_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_sgm_price_snapshots_snapshot_horizon'), ['snapshot_horizon'], unique=False)

    op.create_table('sgm_snapshot_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('leg_index', sa.Integer(), nullable=False),
    sa.Column('leg_type', sa.String(length=16), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('line_value', sa.Float(), nullable=True),
    sa.Column('naive_leg_probability', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('leg_outcome', sa.String(length=16), nullable=True),
    sa.Column('leg_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['sgm_price_snapshots.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'leg_index', name='uq_sgm_snapshot_leg_index')
    )
    with op.batch_alter_table('sgm_snapshot_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sgm_snapshot_legs_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sgm_snapshot_legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sgm_snapshot_legs_snapshot_id'))

    op.drop_table('sgm_snapshot_legs')
    with op.batch_alter_table('sgm_price_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sgm_price_snapshots_snapshot_horizon'))
        batch_op.drop_index(batch_op.f('ix_sgm_price_snapshots_outcome'))
        batch_op.drop_index(batch_op.f('ix_sgm_price_snapshots_model_version'))
        batch_op.drop_index(batch_op.f('ix_sgm_price_snapshots_match_id'))
        batch_op.drop_index(batch_op.f('ix_sgm_price_snapshots_leg_signature'))

    op.drop_table('sgm_price_snapshots')
    # ### end Alembic commands ###
