"""add bookmakers and odds_quotes tables

Revision ID: 45bd7ecc1eb5
Revises: ac23168a1e04
Create Date: 2026-08-14 19:30:25.315863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bd7ecc1eb5'
down_revision: Union[str, None] = 'ac23168a1e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmakers_name'), ['name'], unique=True)

    op.create_table('odds_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('line_value', sa.Float(), nullable=True),
    sa.Column('price_decimal', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_closing_line', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odds_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odds_quotes_bookmaker_id'), ['bookmaker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_quotes_market_type'), ['market_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_quotes_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odds_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odds_quotes_match_id'))
        batch_op.drop_index(batch_op.f('ix_odds_quotes_market_type'))
        batch_op.drop_index(batch_op.f('ix_odds_quotes_bookmaker_id'))

    op.drop_table('odds_quotes')
    with op.batch_alter_table('bookmakers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmakers_name'))

    op.drop_table('bookmakers')
    # ### end Alembic commands ###
