"""add nba minutes model tables

Revision ID: 47742ee9eb7a
Revises: 90343a82a7c8
Create Date: 2026-10-03 21:40:05.083931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47742ee9eb7a'
down_revision: Union[str, None] = '90343a82a7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba_minutes_model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_key', sa.String(length=160), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code_version', sa.String(length=64), nullable=True),
    sa.Column('dataset_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_seasons', sa.JSON(), nullable=False),
    sa.Column('evaluation_seasons', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('uncertainty', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_key', name='uq_nba_minutes_model_run_key')
    )
    with op.batch_alter_table('nba_minutes_model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_minutes_model_runs_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_minutes_model_runs_model_version'), ['model_version'], unique=False)

    op.create_table('nba_minutes_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('information_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_minutes', sa.Float(), nullable=False),
    sa.Column('quantiles', sa.JSON(), nullable=False),
    sa.Column('history_games', sa.Integer(), nullable=False),
    sa.Column('team_source', sa.String(length=32), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['nba_games.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['nba_minutes_model_runs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['nba_players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['nba_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', 'model_run_id', 'information_cutoff', name='uq_nba_minutes_prediction_identity')
    )
    with op.batch_alter_table('nba_minutes_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_minutes_predictions_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_minutes_predictions_information_cutoff'), ['information_cutoff'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_minutes_predictions_model_run_id'), ['model_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_minutes_predictions_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_minutes_predictions_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_minutes_predictions_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nba_minutes_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_minutes_predictions_team_id'))
        batch_op.drop_index(batch_op.f('ix_nba_minutes_predictions_player_id'))
        batch_op.drop_index(batch_op.f('ix_nba_minutes_predictions_model_version'))
        batch_op.drop_index(batch_op.f('ix_nba_minutes_predictions_model_run_id'))
        batch_op.drop_index(batch_op.f('ix_nba_minutes_predictions_information_cutoff'))
        batch_op.drop_index(batch_op.f('ix_nba_minutes_predictions_game_id'))

    op.drop_table('nba_minutes_predictions')
    with op.batch_alter_table('nba_minutes_model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_minutes_model_runs_model_version'))
        batch_op.drop_index(batch_op.f('ix_nba_minutes_model_runs_model_name'))

    op.drop_table('nba_minutes_model_runs')
    # ### end Alembic commands ###
