"""add weekly shortlist snapshots

Revision ID: 4a276e8b7fe4
Revises: c1a4f8e2b9d3
Create Date: 2026-08-18 15:10:56.370426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a276e8b7fe4'
down_revision: Union[str, None] = 'c1a4f8e2b9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_shortlist_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('limit_requested', sa.Integer(), nullable=True),
    sa.Column('include_unconfirmed_players', sa.Boolean(), nullable=False),
    sa.Column('n_items', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_shortlist_snapshot_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('opportunity_type', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('selection', sa.String(length=64), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('line_value', sa.Float(), nullable=True),
    sa.Column('line_type', sa.String(length=16), nullable=True),
    sa.Column('best_price', sa.Float(), nullable=False),
    sa.Column('best_bookmaker', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('model_fair_odds', sa.Float(), nullable=False),
    sa.Column('market_implied_probability', sa.Float(), nullable=False),
    sa.Column('devigged_probability', sa.Float(), nullable=True),
    sa.Column('overround_removed', sa.Boolean(), nullable=False),
    sa.Column('difference_pp', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('confidence_tier', sa.String(length=24), nullable=False),
    sa.Column('quality_tier', sa.String(length=24), nullable=False),
    sa.Column('market_maturity_tier', sa.String(length=24), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('n_bookmakers', sa.Integer(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('actual_stat_value', sa.Float(), nullable=True),
    sa.Column('match_result', sa.String(length=16), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['weekly_shortlist_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_shortlist_snapshot_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_shortlist_snapshot_items_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_shortlist_snapshot_items_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_shortlist_snapshot_items_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_shortlist_snapshot_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_shortlist_snapshot_items_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_shortlist_snapshot_items_player_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_shortlist_snapshot_items_match_id'))

    op.drop_table('weekly_shortlist_snapshot_items')
    op.drop_table('weekly_shortlist_snapshots')
    # ### end Alembic commands ###
