"""add usage regime metadata

Revision ID: 5830752dbad2
Revises: 65cf240c8483
Create Date: 2026-08-23 23:54:22.787438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5830752dbad2'
down_revision: Union[str, None] = '65cf240c8483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_disposal_projections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_regime', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('usage_change_score', sa.Float(), nullable=True))

    with op.batch_alter_table('player_goal_projections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_regime', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('usage_change_score', sa.Float(), nullable=True))

    with op.batch_alter_table('pricing_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_regime_at_prediction', sa.String(length=24), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_snapshots', schema=None) as batch_op:
        batch_op.drop_column('usage_regime_at_prediction')

    with op.batch_alter_table('player_goal_projections', schema=None) as batch_op:
        batch_op.drop_column('usage_change_score')
        batch_op.drop_column('usage_regime')

    with op.batch_alter_table('player_disposal_projections', schema=None) as batch_op:
        batch_op.drop_column('usage_change_score')
        batch_op.drop_column('usage_regime')

    # ### end Alembic commands ###
