"""add player_aliases, live_cycle_runs, observation review flags

Revision ID: 5c2a90036505
Revises: 7860dd9067fc
Create Date: 2026-08-17 16:12:20.284550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2a90036505'
down_revision: Union[str, None] = '7860dd9067fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_cycle_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overall_status', sa.String(length=16), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('odds_credits_consumed', sa.Integer(), nullable=True),
    sa.Column('odds_credits_remaining', sa.Integer(), nullable=True),
    sa.Column('matches_affected', sa.Integer(), nullable=False),
    sa.Column('quotes_added', sa.Integer(), nullable=False),
    sa.Column('observations_added', sa.Integer(), nullable=False),
    sa.Column('observations_settled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name', 'source', name='uq_player_alias_name_source')
    )
    with op.batch_alter_table('player_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_aliases_alias_name'), ['alias_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_aliases_player_id'), ['player_id'], unique=False)

    with op.batch_alter_table('prop_market_observations', schema=None) as batch_op:
        # server_default backfills the 568 existing real observations as
        # not-flagged, an accurate description (review flagging is new;
        # nothing existing was ever actually reviewed-and-flagged).
        batch_op.add_column(sa.Column('needs_review', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('review_reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_market_observations', schema=None) as batch_op:
        batch_op.drop_column('review_reason')
        batch_op.drop_column('needs_review')

    with op.batch_alter_table('player_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_aliases_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_aliases_alias_name'))

    op.drop_table('player_aliases')
    op.drop_table('live_cycle_runs')
    # ### end Alembic commands ###
