"""add model promotion events

Revision ID: 65cf240c8483
Revises: bf102db8bfb2
Create Date: 2026-08-23 22:54:32.481330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cf240c8483'
down_revision: Union[str, None] = 'bf102db8bfb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_promotion_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('previous_champion_model_name', sa.String(length=64), nullable=True),
    sa.Column('previous_champion_model_version', sa.String(length=160), nullable=True),
    sa.Column('new_champion_model_name', sa.String(length=64), nullable=False),
    sa.Column('new_champion_model_version', sa.String(length=160), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_summary', sa.String(length=2000), nullable=False),
    sa.Column('evaluation_metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_promotion_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_promotion_events_market'), ['market'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_promotion_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_promotion_events_market'))

    op.drop_table('model_promotion_events')
    # ### end Alembic commands ###
