"""add goals and behinds to matches

Revision ID: 7032b6846f7e
Revises: 1354f40385f9
Create Date: 2026-08-14 16:57:27.356876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7032b6846f7e'
down_revision: Union[str, None] = '1354f40385f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_goals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_behinds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_goals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_behinds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('away_behinds')
        batch_op.drop_column('away_goals')
        batch_op.drop_column('home_behinds')
        batch_op.drop_column('home_goals')

    # ### end Alembic commands ###
