"""add prospective operation fields and case followups

Revision ID: 71cdf5905ebf
Revises: f9918628bebb
Create Date: 2026-08-24 18:00:39.609037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cdf5905ebf'
down_revision: Union[str, None] = 'f9918628bebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_case_followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('stage_bucket', sa.String(length=16), nullable=False),
    sa.Column('hours_to_kickoff', sa.Float(), nullable=False),
    sa.Column('consensus_probability', sa.Float(), nullable=True),
    sa.Column('model_probability', sa.Float(), nullable=True),
    sa.Column('n_bookmakers', sa.Integer(), nullable=True),
    sa.Column('bookmaker_prices', sa.JSON(), nullable=False),
    sa.Column('lineup_status', sa.String(length=24), nullable=True),
    sa.Column('context_state', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['anomaly_case_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'stage_bucket', name='uq_anomaly_case_followup_snapshot_stage')
    )
    with op.batch_alter_table('anomaly_case_followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_case_followups_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_case_followups_snapshot_id'), ['snapshot_id'], unique=False)

    with op.batch_alter_table('anomaly_case_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capture_mode', sa.String(length=16), nullable=False, server_default='prospective'))
        batch_op.add_column(sa.Column('research_category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('player_prior_games', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('player_season_avg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('player_historical_volume_bucket', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('context_state_latest', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('hours_to_kickoff_latest', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # Data migration: every row that already exists at this point predates
    # the Genuine Prospective Operation stage entirely - each one was
    # created by a one-off retrospective backfill script against already-
    # COMPLETED matches, never by automatic live-cycle freezing. Item 5's
    # boundary (retrospective rows must never count toward primary
    # prospective effectiveness metrics) requires them correctly tagged.
    op.execute("UPDATE anomaly_case_snapshots SET capture_mode = 'retrospective'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_case_snapshots', schema=None) as batch_op:
        batch_op.drop_column('hours_to_kickoff_latest')
        batch_op.drop_column('context_state_latest')
        batch_op.drop_column('player_historical_volume_bucket')
        batch_op.drop_column('player_season_avg')
        batch_op.drop_column('player_prior_games')
        batch_op.drop_column('research_category')
        batch_op.drop_column('capture_mode')

    with op.batch_alter_table('anomaly_case_followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_case_followups_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_case_followups_case_id'))

    op.drop_table('anomaly_case_followups')
    # ### end Alembic commands ###
