"""add nba outlook snapshots

Revision ID: 72256bdebf34
Revises: c133d5a7a11e
Create Date: 2026-10-04 17:01:37.217105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72256bdebf34'
down_revision: Union[str, None] = 'c133d5a7a11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba_outlook_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_label', sa.String(length=16), nullable=False),
    sa.Column('offset_minutes', sa.Integer(), nullable=False),
    sa.Column('scheduled_tipoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('information_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('box_score_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('roster_evidence', sa.JSON(), nullable=False),
    sa.Column('availability_feed_last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_versions', sa.JSON(), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['nba_games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'snapshot_label', 'scheduled_tipoff', name='uq_nba_outlook_snapshot_identity')
    )
    with op.batch_alter_table('nba_outlook_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_outlook_snapshots_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_outlook_snapshots_information_cutoff'), ['information_cutoff'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_outlook_snapshots_snapshot_label'), ['snapshot_label'], unique=False)

    with op.batch_alter_table('nba_rotation_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_nba_rotation_predictions_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_foreign_key('fk_nba_rotation_predictions_snapshot_id', 'nba_outlook_snapshots', ['snapshot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nba_rotation_predictions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_nba_rotation_predictions_snapshot_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_nba_rotation_predictions_snapshot_id'))
        batch_op.drop_column('snapshot_id')

    with op.batch_alter_table('nba_outlook_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_outlook_snapshots_snapshot_label'))
        batch_op.drop_index(batch_op.f('ix_nba_outlook_snapshots_information_cutoff'))
        batch_op.drop_index(batch_op.f('ix_nba_outlook_snapshots_game_id'))

    op.drop_table('nba_outlook_snapshots')
    # ### end Alembic commands ###
