"""add prop market observations

Revision ID: 7860dd9067fc
Revises: 8b18af69553b
Create Date: 2026-08-17 15:06:40.104720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7860dd9067fc'
down_revision: Union[str, None] = '8b18af69553b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prop_market_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('line_type', sa.String(length=16), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('offered_odds', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bookmaker_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_implied_probability', sa.Float(), nullable=False),
    sa.Column('devigged_probability', sa.Float(), nullable=True),
    sa.Column('overround_removed', sa.Boolean(), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('model_fair_odds', sa.Float(), nullable=False),
    sa.Column('predicted_mean', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('data_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_tier', sa.String(length=24), nullable=False),
    sa.Column('selection_status_at_observation', sa.String(length=24), nullable=False),
    sa.Column('is_confirmed_at_observation', sa.Boolean(), nullable=False),
    sa.Column('difference_pp', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('actual_stat_value', sa.Float(), nullable=True),
    sa.Column('market_result', sa.String(length=16), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['player_prop_markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prop_market_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prop_market_observations_bookmaker_id'), ['bookmaker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prop_market_observations_confidence_tier'), ['confidence_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_prop_market_observations_difference_pp'), ['difference_pp'], unique=False)
        batch_op.create_index(batch_op.f('ix_prop_market_observations_market_result'), ['market_result'], unique=False)
        batch_op.create_index(batch_op.f('ix_prop_market_observations_market_type'), ['market_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_prop_market_observations_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prop_market_observations_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prop_market_observations_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prop_market_observations_quote_id'), ['quote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prop_market_observations_selection_status_at_observation'), ['selection_status_at_observation'], unique=False)
        batch_op.create_index(batch_op.f('ix_prop_market_observations_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prop_market_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prop_market_observations_source'))
        batch_op.drop_index(batch_op.f('ix_prop_market_observations_selection_status_at_observation'))
        batch_op.drop_index(batch_op.f('ix_prop_market_observations_quote_id'))
        batch_op.drop_index(batch_op.f('ix_prop_market_observations_player_id'))
        batch_op.drop_index(batch_op.f('ix_prop_market_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_prop_market_observations_match_id'))
        batch_op.drop_index(batch_op.f('ix_prop_market_observations_market_type'))
        batch_op.drop_index(batch_op.f('ix_prop_market_observations_market_result'))
        batch_op.drop_index(batch_op.f('ix_prop_market_observations_difference_pp'))
        batch_op.drop_index(batch_op.f('ix_prop_market_observations_confidence_tier'))
        batch_op.drop_index(batch_op.f('ix_prop_market_observations_bookmaker_id'))

    op.drop_table('prop_market_observations')
    # ### end Alembic commands ###
