"""add model value observations

Revision ID: 78708f13881a
Revises: e2e6f9728ae4
Create Date: 2026-08-31 13:42:31.482606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78708f13881a'
down_revision: Union[str, None] = 'e2e6f9728ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_value_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('value_type', sa.String(length=48), nullable=False),
    sa.Column('value_kind', sa.String(length=24), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('lineup_status', sa.String(length=24), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=160), nullable=False),
    sa.Column('data_cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', 'value_type', 'selection', 'threshold', 'recorded_at', name='uq_model_value_observation_no_exact_dupe')
    )
    with op.batch_alter_table('model_value_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_value_observations_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_value_observations_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_value_observations_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_value_observations_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_value_observations_value_type'), ['value_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_value_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_value_observations_value_type'))
        batch_op.drop_index(batch_op.f('ix_model_value_observations_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_model_value_observations_player_id'))
        batch_op.drop_index(batch_op.f('ix_model_value_observations_model_version'))
        batch_op.drop_index(batch_op.f('ix_model_value_observations_match_id'))

    op.drop_table('model_value_observations')
    # ### end Alembic commands ###
