"""add team external_ids and venue name uniqueness

Revision ID: 8316cece5ae7
Revises: 97b5394b4877
Create Date: 2026-08-14 22:18:25.109702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8316cece5ae7'
down_revision: Union[str, None] = '97b5394b4877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _consolidate_duplicate_venues() -> None:
    """Before the unique constraint can be applied, any venues sharing a
    name (the same key ingestion itself dedupes on) must be merged into one
    row — otherwise the constraint fails to apply on a DB with pre-existing
    duplicates. Keeps the lowest id per name as canonical, repoints every
    match referencing a duplicate onto it, then removes the now-unused
    duplicate rows. Reports what it found; does nothing if there are none.

    Grouping is done in Python (not SQL GROUP_CONCAT, which is SQLite-only
    and broke this migration on Postgres) via SQLAlchemy Core table()
    constructs so the whole function is dialect-portable - discovered
    running this migration against Postgres for the first time."""
    conn = op.get_bind()
    venues = sa.table("venues", sa.column("id", sa.Integer), sa.column("name", sa.String))
    matches = sa.table("matches", sa.column("id", sa.Integer), sa.column("venue_id", sa.Integer))

    rows = conn.execute(sa.select(venues.c.id, venues.c.name).order_by(venues.c.name, venues.c.id)).fetchall()
    groups: dict[str, list[int]] = {}
    for venue_id, name in rows:
        groups.setdefault(name, []).append(venue_id)
    duplicate_groups = {name: ids for name, ids in groups.items() if len(ids) > 1}

    if not duplicate_groups:
        print("  venue uniqueness check: no duplicate venue names found")
        return

    for name, ids in duplicate_groups.items():
        canonical_id, duplicate_ids = ids[0], ids[1:]
        print(f"  duplicate venue {name!r}: ids {ids} -> consolidating onto {canonical_id}")
        for dup_id in duplicate_ids:
            conn.execute(matches.update().where(matches.c.venue_id == dup_id).values(venue_id=canonical_id))
            conn.execute(venues.delete().where(venues.c.id == dup_id))


def upgrade() -> None:
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_ids', sa.JSON(), nullable=True))

    _consolidate_duplicate_venues()

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_venue_name', ['name'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_constraint('uq_venue_name', type_='unique')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('external_ids')

    # ### end Alembic commands ###
