"""add team external_ids and venue name uniqueness

Revision ID: 8316cece5ae7
Revises: 97b5394b4877
Create Date: 2026-08-14 22:18:25.109702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8316cece5ae7'
down_revision: Union[str, None] = '97b5394b4877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _consolidate_duplicate_venues() -> None:
    """Before the unique constraint can be applied, any venues sharing a
    name (the same key ingestion itself dedupes on) must be merged into one
    row — otherwise the constraint fails to apply on a DB with pre-existing
    duplicates. Keeps the lowest id per name as canonical, repoints every
    match referencing a duplicate onto it, then removes the now-unused
    duplicate rows. Reports what it found; does nothing if there are none."""
    conn = op.get_bind()
    duplicate_groups = conn.exec_driver_sql(
        "SELECT name, GROUP_CONCAT(id) FROM venues GROUP BY name HAVING COUNT(*) > 1"
    ).fetchall()

    if not duplicate_groups:
        print("  venue uniqueness check: no duplicate venue names found")
        return

    for name, id_csv in duplicate_groups:
        ids = sorted(int(i) for i in id_csv.split(","))
        canonical_id, duplicate_ids = ids[0], ids[1:]
        print(f"  duplicate venue {name!r}: ids {ids} -> consolidating onto {canonical_id}")
        for dup_id in duplicate_ids:
            conn.exec_driver_sql(
                "UPDATE matches SET venue_id = ? WHERE venue_id = ?", (canonical_id, dup_id)
            )
            conn.exec_driver_sql("DELETE FROM venues WHERE id = ?", (dup_id,))


def upgrade() -> None:
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_ids', sa.JSON(), nullable=True))

    _consolidate_duplicate_venues()

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_venue_name', ['name'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_constraint('uq_venue_name', type_='unique')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('external_ids')

    # ### end Alembic commands ###
