"""add automated player prop odds fields

Revision ID: 8b18af69553b
Revises: 176b3854bd2c
Create Date: 2026-08-16 19:33:51.179377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b18af69553b'
down_revision: Union[str, None] = '176b3854bd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmakers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_key', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=8), nullable=True))

    with op.batch_alter_table('player_prop_markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selection', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('provider_event_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('provider_market_key', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column('bookmaker_last_update', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('raw_outcome', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_player_prop_markets_provider_event_id'), ['provider_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_prop_markets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_prop_markets_provider_event_id'))
        batch_op.drop_column('raw_outcome')
        batch_op.drop_column('bookmaker_last_update')
        batch_op.drop_column('provider_market_key')
        batch_op.drop_column('provider_event_id')
        batch_op.drop_column('selection')

    with op.batch_alter_table('bookmakers', schema=None) as batch_op:
        batch_op.drop_column('region')
        batch_op.drop_column('provider_key')

    # ### end Alembic commands ###
