"""add nba live evidence tables

Revision ID: 90343a82a7c8
Revises: becc7fa40ce6
Create Date: 2026-10-02 23:32:11.535572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90343a82a7c8'
down_revision: Union[str, None] = 'becc7fa40ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba_evidence_polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('observations_added', sa.Integer(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nba_evidence_polls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_evidence_polls_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_evidence_polls_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_evidence_polls_scope'), ['scope'], unique=False)

    op.create_table('nba_live_cycle_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nba_live_cycle_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_live_cycle_runs_started_at'), ['started_at'], unique=False)

    op.create_table('nba_team_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['nba_evidence_polls.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['nba_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nba_team_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_team_observations_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_team_observations_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_team_observations_poll_id'), ['poll_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_team_observations_team_id'), ['team_id'], unique=False)

    op.create_table('nba_game_lineup_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipoff_at_observation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_status_at_observation', sa.String(length=16), nullable=False),
    sa.Column('lineup_available', sa.Boolean(), nullable=True),
    sa.Column('has_starter_field', sa.Boolean(), nullable=False),
    sa.Column('starters_flagged', sa.Integer(), nullable=False),
    sa.Column('players_listed', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['nba_games.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['nba_evidence_polls.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['nba_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nba_game_lineup_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_game_lineup_observations_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_game_lineup_observations_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_game_lineup_observations_poll_id'), ['poll_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_game_lineup_observations_team_id'), ['team_id'], unique=False)

    op.create_table('nba_game_schedule_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_status', sa.String(length=48), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['nba_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nba_game_schedule_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_game_schedule_observations_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nba_game_schedule_observations_observed_at'), ['observed_at'], unique=False)

    with op.batch_alter_table('nba_player_availability_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poll_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_listed', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('source_status_type', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column('injury_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('injury_location', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('injury_side', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('injury_detail', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('fantasy_status', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('expected_return_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('short_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('long_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source_report_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('source_team_id', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('source_athlete_team_id', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('raw', sa.JSON(), nullable=True))
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('source_status',
               existing_type=sa.VARCHAR(length=48),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_nba_player_availability_reports_poll_id'), ['poll_id'], unique=False)
        batch_op.create_foreign_key('fk_nba_player_availability_reports_poll_id', 'nba_evidence_polls', ['poll_id'], ['id'])
        batch_op.drop_column('reason')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nba_player_availability_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint('fk_nba_player_availability_reports_poll_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_nba_player_availability_reports_poll_id'))
        batch_op.alter_column('source_status',
               existing_type=sa.VARCHAR(length=48),
               nullable=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('raw')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('source_athlete_team_id')
        batch_op.drop_column('source_team_id')
        batch_op.drop_column('source_report_id')
        batch_op.drop_column('long_comment')
        batch_op.drop_column('short_comment')
        batch_op.drop_column('expected_return_date')
        batch_op.drop_column('fantasy_status')
        batch_op.drop_column('injury_detail')
        batch_op.drop_column('injury_side')
        batch_op.drop_column('injury_location')
        batch_op.drop_column('injury_type')
        batch_op.drop_column('source_status_type')
        batch_op.drop_column('is_listed')
        batch_op.drop_column('poll_id')

    with op.batch_alter_table('nba_game_schedule_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_game_schedule_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_nba_game_schedule_observations_game_id'))

    op.drop_table('nba_game_schedule_observations')
    with op.batch_alter_table('nba_game_lineup_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_game_lineup_observations_team_id'))
        batch_op.drop_index(batch_op.f('ix_nba_game_lineup_observations_poll_id'))
        batch_op.drop_index(batch_op.f('ix_nba_game_lineup_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_nba_game_lineup_observations_game_id'))

    op.drop_table('nba_game_lineup_observations')
    with op.batch_alter_table('nba_team_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_team_observations_team_id'))
        batch_op.drop_index(batch_op.f('ix_nba_team_observations_poll_id'))
        batch_op.drop_index(batch_op.f('ix_nba_team_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_nba_team_observations_kind'))

    op.drop_table('nba_team_observations')
    with op.batch_alter_table('nba_live_cycle_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_live_cycle_runs_started_at'))

    op.drop_table('nba_live_cycle_runs')
    with op.batch_alter_table('nba_evidence_polls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_evidence_polls_scope'))
        batch_op.drop_index(batch_op.f('ix_nba_evidence_polls_observed_at'))
        batch_op.drop_index(batch_op.f('ix_nba_evidence_polls_kind'))

    op.drop_table('nba_evidence_polls')
    # ### end Alembic commands ###
