"""add model_runs and model_validation_metrics tables

Revision ID: 97b5394b4877
Revises: 45bd7ecc1eb5
Create Date: 2026-08-14 19:58:32.751340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b5394b4877'
down_revision: Union[str, None] = '45bd7ecc1eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('tune_end_year', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', name='uq_model_run_name')
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_runs_model_name'), ['model_name'], unique=False)

    op.create_table('model_validation_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('metric_name', sa.String(length=32), nullable=False),
    sa.Column('holdout_n', sa.Integer(), nullable=False),
    sa.Column('holdout_value', sa.Float(), nullable=False),
    sa.Column('naive_baseline_value', sa.Float(), nullable=False),
    sa.Column('has_edge_over_naive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'market_type', name='uq_validation_run_market')
    )
    with op.batch_alter_table('model_validation_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_validation_metrics_model_run_id'), ['model_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_validation_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_validation_metrics_model_run_id'))

    op.drop_table('model_validation_metrics')
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_runs_model_name'))

    op.drop_table('model_runs')
    # ### end Alembic commands ###
