"""add api consumers keys and usage records

Revision ID: aa33309f94a3
Revises: 78708f13881a
Create Date: 2026-08-31 17:04:10.968757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa33309f94a3'
down_revision: Union[str, None] = '78708f13881a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_consumers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('daily_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_consumers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_consumers_name'), ['name'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumer_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consumer_id'], ['api_consumers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash', name='uq_api_key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_consumer_id'), ['consumer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=False)

    op.create_table('api_usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('consumer_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=256), nullable=True),
    sa.Column('freshness', sa.String(length=16), nullable=True),
    sa.Column('rate_limited', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consumer_id'], ['api_consumers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_records_consumer_id'), ['consumer_id'], unique=False)
        batch_op.create_index('ix_api_usage_records_consumer_recorded', ['consumer_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_records_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_records_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_records_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_records_status_code'), ['status_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_records_status_code'))
        batch_op.drop_index(batch_op.f('ix_api_usage_records_request_id'))
        batch_op.drop_index(batch_op.f('ix_api_usage_records_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_api_usage_records_endpoint'))
        batch_op.drop_index('ix_api_usage_records_consumer_recorded')
        batch_op.drop_index(batch_op.f('ix_api_usage_records_consumer_id'))

    op.drop_table('api_usage_records')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_consumer_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('api_consumers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_consumers_name'))

    op.drop_table('api_consumers')
    # ### end Alembic commands ###
