"""add anomaly alert snapshots

Revision ID: b9a43891bad4
Revises: 5830752dbad2
Create Date: 2026-08-24 16:18:07.017746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a43891bad4'
down_revision: Union[str, None] = '5830752dbad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_alert_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('line_value', sa.Float(), nullable=True),
    sa.Column('model_probability', sa.Float(), nullable=True),
    sa.Column('model_fair_odds', sa.Float(), nullable=True),
    sa.Column('market_consensus_probability', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('lineup_status', sa.String(length=24), nullable=True),
    sa.Column('context_state', sa.String(length=500), nullable=True),
    sa.Column('freshness', sa.String(length=16), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consensus_moved_toward_model', sa.Boolean(), nullable=True),
    sa.Column('outlier_converged', sa.Boolean(), nullable=True),
    sa.Column('stale_market_repriced', sa.Boolean(), nullable=True),
    sa.Column('curve_anomaly_resolved', sa.Boolean(), nullable=True),
    sa.Column('evaluation_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'alert_type', 'market_type', 'selection', 'threshold', 'line_value', 'reason_code', name='uq_anomaly_alert_snapshot_identity')
    )
    with op.batch_alter_table('anomaly_alert_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_alert_snapshots_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_alert_snapshots_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_alert_snapshots_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_alert_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_alert_snapshots_player_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_alert_snapshots_match_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_alert_snapshots_alert_type'))

    op.drop_table('anomaly_alert_snapshots')
    # ### end Alembic commands ###
