"""add nba provenance and ingestion checkpoints

Revision ID: becc7fa40ce6
Revises: 1e453acf52cb
Create Date: 2026-10-02 17:17:48.241971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becc7fa40ce6'
down_revision: Union[str, None] = '1e453acf52cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba_schedule_sync_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('games_kept', sa.Integer(), nullable=False),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'game_date', name='uq_nba_schedule_sync_date_source_date')
    )
    with op.batch_alter_table('nba_schedule_sync_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nba_schedule_sync_dates_game_date'), ['game_date'], unique=False)

    with op.batch_alter_table('nba_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_status', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column('source_season_type', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column('source_synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('box_score_state', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('box_score_synced_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_nba_games_box_score_state'), ['box_score_state'], unique=False)

    with op.batch_alter_table('nba_player_availability_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_status', sa.String(length=48), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    with op.batch_alter_table('nba_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_game_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nba_players', schema=None) as batch_op:
        batch_op.drop_column('last_game_at')

    with op.batch_alter_table('nba_player_availability_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.drop_column('source_status')

    with op.batch_alter_table('nba_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_games_box_score_state'))
        batch_op.drop_column('box_score_synced_at')
        batch_op.drop_column('box_score_state')
        batch_op.drop_column('source_synced_at')
        batch_op.drop_column('source_season_type')
        batch_op.drop_column('source_status')

    with op.batch_alter_table('nba_schedule_sync_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nba_schedule_sync_dates_game_date'))

    op.drop_table('nba_schedule_sync_dates')
    # ### end Alembic commands ###
