"""add pricing snapshots

Revision ID: bf102db8bfb2
Revises: 1817ff671b79
Create Date: 2026-08-23 20:47:46.802134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf102db8bfb2'
down_revision: Union[str, None] = '1817ff671b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('market_family', sa.String(length=16), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('line_type', sa.String(length=16), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('line_value', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lineup_status', sa.String(length=24), nullable=True),
    sa.Column('confidence_tier', sa.String(length=24), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('model_fair_odds', sa.Float(), nullable=False),
    sa.Column('best_bookmaker_price', sa.Float(), nullable=True),
    sa.Column('best_bookmaker_name', sa.String(length=64), nullable=True),
    sa.Column('market_consensus_probability', sa.Float(), nullable=True),
    sa.Column('n_bookmakers', sa.Integer(), nullable=True),
    sa.Column('actual_stat_value', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'market_type', 'selection', 'threshold', 'line_value', 'model_version', name='uq_pricing_snapshot_identity')
    )
    with op.batch_alter_table('pricing_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_snapshots_market_family'), ['market_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_snapshots_market_type'), ['market_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_snapshots_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_snapshots_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_snapshots_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_snapshots_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_snapshots_player_id'))
        batch_op.drop_index(batch_op.f('ix_pricing_snapshots_outcome'))
        batch_op.drop_index(batch_op.f('ix_pricing_snapshots_model_version'))
        batch_op.drop_index(batch_op.f('ix_pricing_snapshots_match_id'))
        batch_op.drop_index(batch_op.f('ix_pricing_snapshots_market_type'))
        batch_op.drop_index(batch_op.f('ix_pricing_snapshots_market_family'))

    op.drop_table('pricing_snapshots')
    # ### end Alembic commands ###
