"""add sgm dependence coefficients

Revision ID: d135a718cc95
Revises: 3d50becab3e5
Create Date: 2026-08-31 11:57:33.459257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd135a718cc95'
down_revision: Union[str, None] = '3d50becab3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgm_dependence_coefficients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('slope', sa.Float(), nullable=False),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('fit_cutoff_year', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('fitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', name='uq_sgm_dependence_coefficient_market')
    )
    with op.batch_alter_table('sgm_dependence_coefficients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sgm_dependence_coefficients_market'), ['market'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sgm_dependence_coefficients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sgm_dependence_coefficients_market'))

    op.drop_table('sgm_dependence_coefficients')
    # ### end Alembic commands ###
