"""widen pricing_snapshots confidence_tier to fit team tier values

Revision ID: d633f77191dc
Revises: ef9db623f17f
Create Date: 2026-08-31 18:50:22.165026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd633f77191dc'
down_revision: Union[str, None] = 'ef9db623f17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_snapshots', schema=None) as batch_op:
        batch_op.alter_column('confidence_tier',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_snapshots', schema=None) as batch_op:
        batch_op.alter_column('confidence_tier',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)

    # ### end Alembic commands ###
