"""add outlook evidence freshness

Revision ID: dd83e713f375
Revises: 72256bdebf34
Create Date: 2026-10-04 17:26:03.313956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd83e713f375'
down_revision: Union[str, None] = '72256bdebf34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nba_outlook_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_freshness', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nba_outlook_snapshots', schema=None) as batch_op:
        batch_op.drop_column('evidence_freshness')

    # ### end Alembic commands ###
