"""add leg type combination to sgm price snapshots

Revision ID: e2e6f9728ae4
Revises: 40dd3e49d0e7
Create Date: 2026-08-31 12:47:11.388781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e6f9728ae4'
down_revision: Union[str, None] = '40dd3e49d0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sgm_price_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leg_type_combination', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_sgm_price_snapshots_leg_type_combination'), ['leg_type_combination'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sgm_price_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sgm_price_snapshots_leg_type_combination'))
        batch_op.drop_column('leg_type_combination')

    # ### end Alembic commands ###
