"""add release_sha to api_usage_records

Revision ID: ef9db623f17f
Revises: aa33309f94a3
Create Date: 2026-08-31 18:24:55.417009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9db623f17f'
down_revision: Union[str, None] = 'aa33309f94a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_sha', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage_records', schema=None) as batch_op:
        batch_op.drop_column('release_sha')

    # ### end Alembic commands ###
