"""add anomaly case snapshots

Revision ID: f9918628bebb
Revises: 2de0af8855ae
Create Date: 2026-08-24 17:03:58.973750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9918628bebb'
down_revision: Union[str, None] = '2de0af8855ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_case_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('line_value', sa.Float(), nullable=True),
    sa.Column('alert_types', sa.JSON(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_components', sa.JSON(), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('market_consensus_probability_at_freeze', sa.Float(), nullable=True),
    sa.Column('bookmaker_prices_at_freeze', sa.JSON(), nullable=False),
    sa.Column('n_bookmakers_at_freeze', sa.Integer(), nullable=False),
    sa.Column('earliest_quote_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_quote_at_freeze', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lineup_status', sa.String(length=24), nullable=True),
    sa.Column('context_state', sa.String(length=500), nullable=True),
    sa.Column('model_risk_flags', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('persistence_n_snapshots_at_freeze', sa.Integer(), nullable=False),
    sa.Column('time_to_kickoff_hours_at_freeze', sa.Float(), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_consensus_probability_latest', sa.Float(), nullable=True),
    sa.Column('model_probability_latest', sa.Float(), nullable=True),
    sa.Column('n_bookmakers_latest', sa.Integer(), nullable=True),
    sa.Column('latest_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('n_prekickoff_refreshes', sa.Integer(), nullable=False),
    sa.Column('outcome_codes', sa.JSON(), nullable=True),
    sa.Column('outlier_converged', sa.Boolean(), nullable=True),
    sa.Column('stale_market_repriced', sa.Boolean(), nullable=True),
    sa.Column('curve_anomaly_resolved', sa.Boolean(), nullable=True),
    sa.Column('actual_stat_value', sa.Float(), nullable=True),
    sa.Column('actual_outcome_note', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_to_resolution_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_anomaly_case_snapshot_case_id')
    )
    with op.batch_alter_table('anomaly_case_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_case_snapshots_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_case_snapshots_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_case_snapshots_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_case_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_case_snapshots_player_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_case_snapshots_match_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_case_snapshots_case_id'))

    op.drop_table('anomaly_case_snapshots')
    # ### end Alembic commands ###
