"""add expected lineups, player projections, player prop markets

Revision ID: fda3962cc07c
Revises: 401893bb030b
Create Date: 2026-08-16 15:58:40.256520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda3962cc07c'
down_revision: Union[str, None] = '401893bb030b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expected_lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('substitute_risk', sa.Boolean(), nullable=False),
    sa.Column('returning_from_injury', sa.Boolean(), nullable=False),
    sa.Column('role_note', sa.String(length=200), nullable=True),
    sa.Column('expected_tog_adjustment', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_expected_lineup_match_player')
    )
    with op.batch_alter_table('expected_lineups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expected_lineups_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expected_lineups_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expected_lineups_team_id'), ['team_id'], unique=False)

    op.create_table('player_disposal_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lineup_status_at_generation', sa.String(length=16), nullable=False),
    sa.Column('games_of_history', sa.Integer(), nullable=False),
    sa.Column('predicted_mean', sa.Float(), nullable=False),
    sa.Column('distribution_method', sa.String(length=32), nullable=False),
    sa.Column('nb_alpha', sa.Float(), nullable=True),
    sa.Column('confidence_tier', sa.String(length=24), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('input_features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_player_disposal_projection_match_player')
    )
    with op.batch_alter_table('player_disposal_projections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_disposal_projections_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_disposal_projections_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_disposal_projections_team_id'), ['team_id'], unique=False)

    op.create_table('player_goal_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lineup_status_at_generation', sa.String(length=16), nullable=False),
    sa.Column('games_of_history', sa.Integer(), nullable=False),
    sa.Column('predicted_mean', sa.Float(), nullable=False),
    sa.Column('distribution_kind', sa.String(length=32), nullable=False),
    sa.Column('nb_alpha', sa.Float(), nullable=True),
    sa.Column('p_score', sa.Float(), nullable=True),
    sa.Column('mu_scored', sa.Float(), nullable=True),
    sa.Column('alpha_scored', sa.Float(), nullable=True),
    sa.Column('scoring_archetype', sa.String(length=24), nullable=False),
    sa.Column('confidence_tier', sa.String(length=24), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('input_features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_player_goal_projection_match_player')
    )
    with op.batch_alter_table('player_goal_projections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_goal_projections_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_goal_projections_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_goal_projections_team_id'), ['team_id'], unique=False)

    op.create_table('player_prop_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('line_type', sa.String(length=16), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('price_decimal', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_prop_markets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_prop_markets_bookmaker_id'), ['bookmaker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_prop_markets_market_type'), ['market_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_prop_markets_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_prop_markets_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_prop_markets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_prop_markets_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_prop_markets_match_id'))
        batch_op.drop_index(batch_op.f('ix_player_prop_markets_market_type'))
        batch_op.drop_index(batch_op.f('ix_player_prop_markets_bookmaker_id'))

    op.drop_table('player_prop_markets')
    with op.batch_alter_table('player_goal_projections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_goal_projections_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_goal_projections_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_goal_projections_match_id'))

    op.drop_table('player_goal_projections')
    with op.batch_alter_table('player_disposal_projections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_disposal_projections_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_disposal_projections_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_disposal_projections_match_id'))

    op.drop_table('player_disposal_projections')
    with op.batch_alter_table('expected_lineups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expected_lineups_team_id'))
        batch_op.drop_index(batch_op.f('ix_expected_lineups_player_id'))
        batch_op.drop_index(batch_op.f('ix_expected_lineups_match_id'))

    op.drop_table('expected_lineups')
    # ### end Alembic commands ###
